title: "Kiran"
description: "Personal website"
theme: minima
author: Kiran
markdown: kramdown

# Add navigation links to show in top menu
header_pages:
  - index.md
  - projects.md
  - nonlinear-constraints.md
