title: "Kiran"
description: "Personal website"
theme: minima
author: Kiran
markdown: kramdown

# Navigation menu
nav:
  - name: "Home"
    link: "/"
  - name: "Projects"
    link: "/projects"
  - name: "Technical Notes"
    link: "/notes/nonlinear-constraints"
